apiVersion: v1
kind: Service
metadata:
  name: karthi-service
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    run: karthi-service
